-- Auto-generated save compatibility layer.
-- Batch 8 of 8 (50 mappings)
-- Registers old kyno_ prefab names as wrappers that delegate to sap_ equivalents.
-- Generated by tools/generate_compat.py

local prefabs = {}

local legacy_map = {
	["kyno_wildbore"] = "sap_wildbore",
	["kyno_wildbore_head"] = "sap_wildbore_head",
	["kyno_wildbore_house"] = "sap_wildbore_house",
	["kyno_willowhead"] = "sap_willowhead",
	["kyno_willowskull"] = "sap_willowskull",
	["kyno_wilsonhead"] = "sap_wilsonhead",
	["kyno_wilsonskull"] = "sap_wilsonskull",
	["kyno_wiltonskull"] = "sap_wiltonskull",
	["kyno_winnieskull"] = "sap_winnieskull",
	["kyno_winonahead"] = "sap_winonahead",
	["kyno_winonaskull"] = "sap_winonaskull",
	["kyno_wishingwell"] = "sap_wishingwell",
	["kyno_wobster_den"] = "sap_wobster_den",
	["kyno_wolfganghead"] = "sap_wolfganghead",
	["kyno_wolfgangskull"] = "sap_wolfgangskull",
	["kyno_wonkeyhead"] = "sap_wonkeyhead",
	["kyno_wonkeyskull"] = "sap_wonkeyskull",
	["kyno_woodiehead"] = "sap_woodiehead",
	["kyno_woodieskull"] = "sap_woodieskull",
	["kyno_woodlegs_cage"] = "sap_woodlegs_cage",
	["kyno_woodlegshead"] = "sap_woodlegshead",
	["kyno_workbench"] = "sap_workbench",
	["kyno_wormhole"] = "sap_wormhole",
	["kyno_wormhole_ham"] = "sap_wormhole_ham",
	["kyno_wormhole_sick"] = "sap_wormhole_sick",
	["kyno_wormhole_sw"] = "sap_wormhole_sw",
	["kyno_wormlight"] = "sap_wormlight",
	["kyno_wormlight_real"] = "sap_wormlight_real",
	["kyno_wormwoodhead"] = "sap_wormwoodhead",
	["kyno_wormwoodskull"] = "sap_wormwoodskull",
	["kyno_worshipper"] = "sap_worshipper",
	["kyno_worshipper2"] = "sap_worshipper2",
	["kyno_worshipper2_left"] = "sap_worshipper2_left",
	["kyno_wortoxhead"] = "sap_wortoxhead",
	["kyno_wortoxskull"] = "sap_wortoxskull",
	["kyno_wreck_1"] = "sap_wreck_1",
	["kyno_wreck_2"] = "sap_wreck_2",
	["kyno_wreck_3"] = "sap_wreck_3",
	["kyno_wreck_4"] = "sap_wreck_4",
	["kyno_wurthead"] = "sap_wurthead",
	["kyno_wurtskull"] = "sap_wurtskull",
	["kyno_wx78head"] = "sap_wx78head",
	["kyno_wx78skull"] = "sap_wx78skull",
	["kyno_wx_mech"] = "sap_wx_mech",
	["kyno_yellowflies"] = "sap_yellowflies",
	["kyno_yotb_rug"] = "sap_yotb_rug",
	["kyno_yotc_rug"] = "sap_yotc_rug",
	["kyno_zeb"] = "sap_zeb",
	["kyno_zeb_builder"] = "sap_zeb_builder",
	["kyno_zeb_herd"] = "sap_zeb_herd",
}

for old_name, new_name in pairs(legacy_map) do
	local function fn()
		return SpawnPrefab(new_name)
	end
	table.insert(prefabs, Prefab(old_name, fn))
end

return unpack(prefabs)
