#!/usr/bin/env python3
"""
Generate scripts/prefabs/k_legacy_compat*.lua from rename_map.json.

Creates multiple prefab files (batched to stay under Lua 5.1's unpack limit)
that register all old kyno_ names as SpawnPrefab wrappers pointing to sap_ names.
"""

import json
from pathlib import Path

MOD_ROOT = Path(__file__).parent.parent
BATCH_SIZE = 200  # Well under Lua 5.1's ~250 return value limit


def main():
    map_path = MOD_ROOT / "tools" / "rename_map.json"
    with open(map_path) as f:
        rename_map = json.load(f)

    # Collect prefab_name entries (non-placer)
    mappings = []
    for old_name, info in sorted(rename_map.items()):
        if info.get("category") == "prefab_name" and not old_name.endswith("_placer"):
            new_name = info["new_name"]
            mappings.append((old_name, new_name))

    # Split into batches
    batches = []
    for i in range(0, len(mappings), BATCH_SIZE):
        batches.append(mappings[i:i + BATCH_SIZE])

    filenames = []

    for batch_idx, batch in enumerate(batches):
        suffix = "" if batch_idx == 0 else str(batch_idx + 1)
        filename = f"k_legacy_compat{suffix}"
        filenames.append(filename)
        output_path = MOD_ROOT / "scripts" / "prefabs" / f"{filename}.lua"

        lines = []
        lines.append("-- Auto-generated save compatibility layer.")
        lines.append(f"-- Batch {batch_idx + 1} of {len(batches)} ({len(batch)} mappings)")
        lines.append("-- Registers old kyno_ prefab names as wrappers that delegate to sap_ equivalents.")
        lines.append("-- Generated by tools/generate_compat.py")
        lines.append("")
        lines.append("local prefabs = {}")
        lines.append("")
        lines.append("local legacy_map = {")

        for old_name, new_name in batch:
            lines.append(f'\t["{old_name}"] = "{new_name}",')

        lines.append("}")
        lines.append("")
        lines.append("for old_name, new_name in pairs(legacy_map) do")
        lines.append("\tlocal function fn()")
        lines.append("\t\treturn SpawnPrefab(new_name)")
        lines.append("\tend")
        lines.append("\ttable.insert(prefabs, Prefab(old_name, fn))")
        lines.append("end")
        lines.append("")
        lines.append("return unpack(prefabs)")
        lines.append("")

        with open(output_path, "w") as f:
            f.write("\n".join(lines))

        print(f"Generated {output_path} ({len(batch)} mappings)")

    print(f"\nTotal: {len(mappings)} mappings in {len(batches)} files")
    print(f"\nAdd to tap_prefabs.lua PrefabFiles:")
    for fn in filenames:
        print(f'\t"{fn}",')


if __name__ == "__main__":
    main()
